### ISSUE TITLE
Stage example missing build artefact

### ISSUE THREAD

**Issue by StefanSchoof** [MicrosoftDocs/pipelines-multistage#3]
The Build-test-staging-prod checks in every stage the source repro out. A real life use case needs to get the build artefact from the build stage.

**Comment by wimdows-nl** [comment]
Hi @StefanSchoof - the examples are missing the deployment job, see: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/deployment-jobs?view=azure-devops

Beyond the Build stage, you may want to use those instead of the 'normal' jobs. Those deployment jobs will download your build artifacts.
Note that you will have to setup Environments for this first, as deployment jobs require an associated environment.

E.g.:
```
- stage: Deploy
  jobs:
  - deployment: DeployJob
    displayName: Deploy Job
    pool:
      name: 'YourAgentPool'
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Hello
```

**Comment by StefanSchoof** [comment]
Thanks for the answer. This helps me to getting further. But I did not find how the path for the build artefacts and how to access them best.

In my case I have two different build artefact, which I need on to different agents for deployment (one onprem and one hosted)

**Comment by wimdows-nl** [comment]
You can use the PublishBuildArtifacts task, see: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops
```
        - task: PublishBuildArtifacts@1
          displayName: 'Publish artifact'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: 'YourArtifact'
```

The deploy job should grab the build artifacts automatically.
